name: Package

on: [push]

jobs:
  build_ux:
    name: Rust project on unix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - uses: actions-rs/cargo@v1
        with:
          command: build
          toolchain: nightly
          args: --release --all-features
      - name: Rename binary
        run: mv target/release/simple-code-server target/release/simple-code-server-amd64
  build_win:
    name: Rust project on windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - uses: actions-rs/cargo@v1
        with:
          command: build
          toolchain: nightly
          args: --release --all-features
  build_osx:
    name: Rust project on macox
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: x86_64-apple-darwin
      - uses: actions-rs/cargo@v1
        with:
          command: build
          toolchain: nightly
          args: --release --all-features
      - name: Rename binary
        run: mv target/release/simple-code-server target/release/simple-code-server-osx
